# Fonts
font_family Iosevka
bold_italic_font auto
font_size 18

# Window
window_padding_width 12 16
background_opacity 1
hide_window_decorations yes
scrollback_indicator_opacity 0.0

# Cursor
cursor_trail 10
cursor_trail_start_threshold 0
cursor_trail_decay 0.01 0.15
cursor_shape block
cursor_blink_interval 0
shell_integration no-cursor

# Behavior
enable_audio_bello no
confirm_os_window_close 0
allow_remote_control yes

# Colors — Waybar-inspired, Vim-friendly
background #000000
foreground #c0c0c0

cursor #ffffff
cursor_text_color #000000

selection_foreground #000000
selection_background #c0c0c0

# Normal ANSI
color0  #111111
color1  #c45c5c
color2  #9aaa7a
color3  #b09a70
color4  #7f9fba
color5  #9a8faa
color6  #7fa8a8
color7  #c0c0c0

# Bright ANSI
color8  #444444
color9  #e07070
color10 #b0c890
color11 #c4ad80
color12 #9ab8d0
color13 #b0a0c0
color14 #9ac0c0
color15 #ffffff
